set -g status-right ""
set -g status-left ""
set -g status-left-length 0
set -g window-status-current-format "#I:#{=7:window_name}"
set -g window-status-format "#I:#{=7:window_name}"
set -g focus-events on
set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_command}"
set -g status-style "bg=default,fg=white"

set -g mouse on
set -g history-limit 1000000
setw -g mode-keys vi
bind -n M-Up copy-mode
